global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loadbalancer'
    static_configs:
      - targets: ['loadbalancer:8080']
  - job_name: 'backend1'
    static_configs:
      - targets: ['backend1:8081']
  - job_name: 'backend2'
    static_configs:
      - targets: ['backend2:8082']
  - job_name: 'backend3'
    static_configs:
      - targets: ['backend3:8083']
